LEFT_CAMERA_NAME = 'CameraRGB_L_{:0>6d}.png'
CENTER_CAMERA_NAME = 'CameraRGB_C_{:0>6d}.png'
RIGHT_CAMERA_NAME = 'CameraRGB_R_{:0>6d}.png'

MEASUREMENTS_CSV_FILENAME = 'measurements.csv'

MINIMAL_SPEED = 15
MAXIMAL_SPEED = 25
USE_SPEED_CONSTRAINTS = True